// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (*UserRole, error)
	CalculateTotalPrice(ctx context.Context, orderID int32) (int32, error)
	CreateCart(ctx context.Context, arg CreateCartParams) (*Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	// Create Merchant
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (*Merchant, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (*OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (*Product, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (*RefreshToken, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (*Review, error)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	CreateShippingAddress(ctx context.Context, arg CreateShippingAddressParams) (*ShippingAddress, error)
	CreateSlider(ctx context.Context, arg CreateSliderParams) (*Slider, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (*Transaction, error)
	// Create User
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteAllCart(ctx context.Context, dollar_1 []int32) error
	// Delete All Trashed Category Permanently
	DeleteAllPermanentCategories(ctx context.Context) error
	// Delete All Trashed Merchant Permanently
	DeleteAllPermanentMerchants(ctx context.Context) error
	DeleteAllPermanentOrders(ctx context.Context) error
	// Delete All Trashed Order Item Permanently
	DeleteAllPermanentOrdersItem(ctx context.Context) error
	// Delete All Trashed Product Permanently
	DeleteAllPermanentProducts(ctx context.Context) error
	DeleteAllPermanentReviews(ctx context.Context) error
	// Delete All Trashed Roles Permanently
	DeleteAllPermanentRoles(ctx context.Context) error
	DeleteAllPermanentShippingAddress(ctx context.Context) error
	DeleteAllPermanentSliders(ctx context.Context) error
	// Delete All Trashed Transaction Permanently
	DeleteAllPermanentTransactions(ctx context.Context) error
	// Delete All Trashed Users Permanently
	DeleteAllPermanentUsers(ctx context.Context) error
	DeleteCart(ctx context.Context, cartID int32) error
	// Delete Category Permanently
	DeleteCategoryPermanently(ctx context.Context, categoryID int32) error
	// Delete Merchant Permanently
	DeleteMerchantPermanently(ctx context.Context, merchantID int32) error
	// Delete Order Item Permanently
	DeleteOrderItemPermanently(ctx context.Context, orderID int32) error
	DeleteOrderPermanently(ctx context.Context, orderID int32) error
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// Delete Product Permanently
	DeleteProductPermanently(ctx context.Context, productID int32) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRefreshTokenByUserId(ctx context.Context, userID int32) error
	DeleteReviewPermanently(ctx context.Context, reviewID int32) error
	DeleteShippingAddressPermanently(ctx context.Context, shippingAddressID int32) error
	DeleteSliderPermanently(ctx context.Context, sliderID int32) error
	// Delete Transaction Permanently
	DeleteTransactionPermanently(ctx context.Context, transactionID int32) error
	// Delete User Permanently
	DeleteUserPermanently(ctx context.Context, userID int32) error
	FindRefreshTokenByToken(ctx context.Context, token string) (*RefreshToken, error)
	FindRefreshTokenByUserId(ctx context.Context, userID int32) (*RefreshToken, error)
	// Get All Active Roles
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	GetCarts(ctx context.Context, arg GetCartsParams) ([]*GetCartsRow, error)
	// Get Categories with Pagination and Total Count
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]*GetCategoriesRow, error)
	// Get Active Categories with Pagination and Total Count
	GetCategoriesActive(ctx context.Context, arg GetCategoriesActiveParams) ([]*GetCategoriesActiveRow, error)
	// Get Trashed Categories with Pagination and Total Count
	GetCategoriesTrashed(ctx context.Context, arg GetCategoriesTrashedParams) ([]*GetCategoriesTrashedRow, error)
	GetCategoryByID(ctx context.Context, categoryID int32) (*Category, error)
	GetMerchantByID(ctx context.Context, merchantID int32) (*Merchant, error)
	GetMerchants(ctx context.Context, arg GetMerchantsParams) ([]*GetMerchantsRow, error)
	// Get Active Merchants with Pagination and Total Count
	GetMerchantsActive(ctx context.Context, arg GetMerchantsActiveParams) ([]*GetMerchantsActiveRow, error)
	// Get Trashed Merchants with Pagination and Total Count
	GetMerchantsTrashed(ctx context.Context, arg GetMerchantsTrashedParams) ([]*GetMerchantsTrashedRow, error)
	GetOrderByID(ctx context.Context, orderID int32) (*Order, error)
	// Get Order Items  with Pagination and Total Count
	GetOrderItems(ctx context.Context, arg GetOrderItemsParams) ([]*GetOrderItemsRow, error)
	// Get Active Order Item with Pagination and Total Count
	GetOrderItemsActive(ctx context.Context, arg GetOrderItemsActiveParams) ([]*GetOrderItemsActiveRow, error)
	GetOrderItemsByOrder(ctx context.Context, orderID int32) ([]*OrderItem, error)
	// Get Trashed Orders Items with Pagination and Total Count
	GetOrderItemsTrashed(ctx context.Context, arg GetOrderItemsTrashedParams) ([]*GetOrderItemsTrashedRow, error)
	GetOrders(ctx context.Context, arg GetOrdersParams) ([]*GetOrdersRow, error)
	GetOrdersActive(ctx context.Context, arg GetOrdersActiveParams) ([]*GetOrdersActiveRow, error)
	GetOrdersByMerchant(ctx context.Context, arg GetOrdersByMerchantParams) ([]*GetOrdersByMerchantRow, error)
	GetOrdersTrashed(ctx context.Context, arg GetOrdersTrashedParams) ([]*GetOrdersTrashedRow, error)
	GetProductByID(ctx context.Context, productID int32) (*Product, error)
	GetProducts(ctx context.Context, arg GetProductsParams) ([]*GetProductsRow, error)
	// Get Active Products with Pagination and Total Count
	GetProductsActive(ctx context.Context, arg GetProductsActiveParams) ([]*GetProductsActiveRow, error)
	// Get Products by Category Name with Filters
	GetProductsByCategoryName(ctx context.Context, arg GetProductsByCategoryNameParams) ([]*GetProductsByCategoryNameRow, error)
	GetProductsByMerchant(ctx context.Context, arg GetProductsByMerchantParams) ([]*GetProductsByMerchantRow, error)
	// Get Trashed Products with Pagination and Total Count
	GetProductsTrashed(ctx context.Context, arg GetProductsTrashedParams) ([]*GetProductsTrashedRow, error)
	GetReviewByID(ctx context.Context, reviewID int32) (*Review, error)
	GetReviews(ctx context.Context, arg GetReviewsParams) ([]*GetReviewsRow, error)
	GetReviewsActive(ctx context.Context, arg GetReviewsActiveParams) ([]*GetReviewsActiveRow, error)
	GetReviewsByProductID(ctx context.Context, arg GetReviewsByProductIDParams) ([]*GetReviewsByProductIDRow, error)
	GetReviewsTrashed(ctx context.Context, arg GetReviewsTrashedParams) ([]*GetReviewsTrashedRow, error)
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	GetShippingAddress(ctx context.Context, arg GetShippingAddressParams) ([]*GetShippingAddressRow, error)
	GetShippingAddressActive(ctx context.Context, arg GetShippingAddressActiveParams) ([]*GetShippingAddressActiveRow, error)
	GetShippingAddressByOrderID(ctx context.Context, orderID int32) (*ShippingAddress, error)
	GetShippingAddressTrashed(ctx context.Context, arg GetShippingAddressTrashedParams) ([]*GetShippingAddressTrashedRow, error)
	GetShippingByID(ctx context.Context, shippingAddressID int32) (*ShippingAddress, error)
	GetSliderByID(ctx context.Context, sliderID int32) (*Slider, error)
	GetSliders(ctx context.Context, arg GetSlidersParams) ([]*GetSlidersRow, error)
	GetSlidersActive(ctx context.Context, arg GetSlidersActiveParams) ([]*GetSlidersActiveRow, error)
	GetSlidersTrashed(ctx context.Context, arg GetSlidersTrashedParams) ([]*GetSlidersTrashedRow, error)
	GetTransactionByID(ctx context.Context, transactionID int32) (*Transaction, error)
	GetTransactionByMerchant(ctx context.Context, arg GetTransactionByMerchantParams) ([]*GetTransactionByMerchantRow, error)
	GetTransactionByOrderID(ctx context.Context, orderID int32) (*Transaction, error)
	GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]*GetTransactionsRow, error)
	// Get Active Transactions with Pagination and Total Count
	GetTransactionsActive(ctx context.Context, arg GetTransactionsActiveParams) ([]*GetTransactionsActiveRow, error)
	// Get Trashed Transactions with Pagination and Total Count
	GetTransactionsTrashed(ctx context.Context, arg GetTransactionsTrashedParams) ([]*GetTransactionsTrashedRow, error)
	// Get All Trashed Roles
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	GetTrashedUserRoles(ctx context.Context, userID int32) ([]*GetTrashedUserRolesRow, error)
	// Get User by Email
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	// Get User by ID
	GetUserByID(ctx context.Context, userID int32) (*User, error)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// Get Trashed Users with Pagination and Total Count
	GetUserTrashed(ctx context.Context, arg GetUserTrashedParams) ([]*GetUserTrashedRow, error)
	// Get Users with Pagination and Total Count
	GetUsers(ctx context.Context, arg GetUsersParams) ([]*GetUsersRow, error)
	// Get Active Users with Pagination and Total Count
	GetUsersActive(ctx context.Context, arg GetUsersActiveParams) ([]*GetUsersActiveRow, error)
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	// Restore All Trashed Category
	RestoreAllCategories(ctx context.Context) error
	// Restore All Trashed Merchant
	RestoreAllMerchants(ctx context.Context) error
	RestoreAllOrders(ctx context.Context) error
	// Restore All Trashed Order Item
	RestoreAllOrdersItem(ctx context.Context) error
	// Restore All Trashed Product
	RestoreAllProducts(ctx context.Context) error
	RestoreAllReviews(ctx context.Context) error
	// Restore All Trashed Roles
	RestoreAllRoles(ctx context.Context) error
	RestoreAllShippingAddress(ctx context.Context) error
	RestoreAllSliders(ctx context.Context) error
	// Restore All Trashed Transaction
	RestoreAllTransactions(ctx context.Context) error
	// Restore All Trashed Users
	RestoreAllUsers(ctx context.Context) error
	// Restore Trashed Category
	RestoreCategory(ctx context.Context, categoryID int32) (*Category, error)
	// Restore Trashed Merchant
	RestoreMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	RestoreOrder(ctx context.Context, orderID int32) (*Order, error)
	// Restore Trashed Order Item
	RestoreOrderItem(ctx context.Context, orderID int32) (*OrderItem, error)
	// Restore Trashed Product
	RestoreProduct(ctx context.Context, productID int32) (*Product, error)
	RestoreReview(ctx context.Context, reviewID int32) (*Review, error)
	RestoreRole(ctx context.Context, roleID int32) error
	RestoreShippingAddress(ctx context.Context, shippingAddressID int32) (*ShippingAddress, error)
	RestoreSlider(ctx context.Context, sliderID int32) (*Slider, error)
	// Restore Trashed Transaction
	RestoreTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// Restore Trashed User
	RestoreUser(ctx context.Context, userID int32) (*User, error)
	RestoreUserRole(ctx context.Context, userRoleID int32) error
	// Trash Category
	TrashCategory(ctx context.Context, categoryID int32) (*Category, error)
	// Trash Merchant
	TrashMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	TrashOrder(ctx context.Context, orderID int32) (*Order, error)
	// Trash Order Item
	TrashOrderItem(ctx context.Context, orderID int32) (*OrderItem, error)
	// Trash Product
	TrashProduct(ctx context.Context, productID int32) (*Product, error)
	TrashReview(ctx context.Context, reviewID int32) (*Review, error)
	TrashRole(ctx context.Context, roleID int32) error
	TrashShippingAddress(ctx context.Context, shippingAddressID int32) (*ShippingAddress, error)
	TrashSlider(ctx context.Context, sliderID int32) (*Slider, error)
	// Trash Transaction
	TrashTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// Trash User
	TrashUser(ctx context.Context, userID int32) (*User, error)
	TrashUserRole(ctx context.Context, userRoleID int32) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	// Update Merchant
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (*Merchant, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (*Order, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (*OrderItem, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (*Product, error)
	UpdateProductCountStock(ctx context.Context, arg UpdateProductCountStockParams) (*Product, error)
	UpdateRefreshTokenByUserId(ctx context.Context, arg UpdateRefreshTokenByUserIdParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (*Review, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	UpdateShippingAddress(ctx context.Context, arg UpdateShippingAddressParams) (*ShippingAddress, error)
	UpdateSlider(ctx context.Context, arg UpdateSliderParams) (*Slider, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (*Transaction, error)
	// Update User
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
