// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sliders.sql

package db

import (
	"context"
	"database/sql"
)

const createSlider = `-- name: CreateSlider :one
INSERT INTO sliders (name, image)
VALUES ($1, $2)
RETURNING slider_id, name, image, created_at, updated_at, deleted_at
`

type CreateSliderParams struct {
	Name  string `json:"name"`
	Image string `json:"image"`
}

func (q *Queries) CreateSlider(ctx context.Context, arg CreateSliderParams) (*Slider, error) {
	row := q.db.QueryRowContext(ctx, createSlider, arg.Name, arg.Image)
	var i Slider
	err := row.Scan(
		&i.SliderID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteAllPermanentSliders = `-- name: DeleteAllPermanentSliders :exec
DELETE FROM sliders
WHERE deleted_at IS NOT NULL
`

func (q *Queries) DeleteAllPermanentSliders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPermanentSliders)
	return err
}

const deleteSliderPermanently = `-- name: DeleteSliderPermanently :exec
DELETE FROM sliders WHERE slider_id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) DeleteSliderPermanently(ctx context.Context, sliderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteSliderPermanently, sliderID)
	return err
}

const getSliderByID = `-- name: GetSliderByID :one
SELECT slider_id, name, image, created_at, updated_at, deleted_at
FROM sliders
WHERE slider_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetSliderByID(ctx context.Context, sliderID int32) (*Slider, error) {
	row := q.db.QueryRowContext(ctx, getSliderByID, sliderID)
	var i Slider
	err := row.Scan(
		&i.SliderID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getSliders = `-- name: GetSliders :many
SELECT
    slider_id, name, image, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM sliders
WHERE deleted_at IS NULL
AND ($1::TEXT IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetSlidersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetSlidersRow struct {
	SliderID   int32        `json:"slider_id"`
	Name       string       `json:"name"`
	Image      string       `json:"image"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	TotalCount int64        `json:"total_count"`
}

func (q *Queries) GetSliders(ctx context.Context, arg GetSlidersParams) ([]*GetSlidersRow, error) {
	rows, err := q.db.QueryContext(ctx, getSliders, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetSlidersRow
	for rows.Next() {
		var i GetSlidersRow
		if err := rows.Scan(
			&i.SliderID,
			&i.Name,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlidersActive = `-- name: GetSlidersActive :many
SELECT
    slider_id, name, image, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM sliders
WHERE deleted_at IS NULL
AND ($1::TEXT IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetSlidersActiveParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetSlidersActiveRow struct {
	SliderID   int32        `json:"slider_id"`
	Name       string       `json:"name"`
	Image      string       `json:"image"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	TotalCount int64        `json:"total_count"`
}

func (q *Queries) GetSlidersActive(ctx context.Context, arg GetSlidersActiveParams) ([]*GetSlidersActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, getSlidersActive, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetSlidersActiveRow
	for rows.Next() {
		var i GetSlidersActiveRow
		if err := rows.Scan(
			&i.SliderID,
			&i.Name,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlidersTrashed = `-- name: GetSlidersTrashed :many
SELECT
    slider_id, name, image, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM sliders
WHERE deleted_at IS NOT NULL
AND ($1::TEXT IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetSlidersTrashedParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetSlidersTrashedRow struct {
	SliderID   int32        `json:"slider_id"`
	Name       string       `json:"name"`
	Image      string       `json:"image"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	TotalCount int64        `json:"total_count"`
}

func (q *Queries) GetSlidersTrashed(ctx context.Context, arg GetSlidersTrashedParams) ([]*GetSlidersTrashedRow, error) {
	rows, err := q.db.QueryContext(ctx, getSlidersTrashed, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetSlidersTrashedRow
	for rows.Next() {
		var i GetSlidersTrashedRow
		if err := rows.Scan(
			&i.SliderID,
			&i.Name,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAllSliders = `-- name: RestoreAllSliders :exec
UPDATE sliders
SET deleted_at = NULL
WHERE deleted_at IS NOT NULL
`

func (q *Queries) RestoreAllSliders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, restoreAllSliders)
	return err
}

const restoreSlider = `-- name: RestoreSlider :one
UPDATE sliders
SET deleted_at = NULL
WHERE slider_id = $1
AND deleted_at IS NOT NULL
RETURNING slider_id, name, image, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreSlider(ctx context.Context, sliderID int32) (*Slider, error) {
	row := q.db.QueryRowContext(ctx, restoreSlider, sliderID)
	var i Slider
	err := row.Scan(
		&i.SliderID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashSlider = `-- name: TrashSlider :one
UPDATE sliders
SET deleted_at = CURRENT_TIMESTAMP
WHERE slider_id = $1
AND deleted_at IS NULL
RETURNING slider_id, name, image, created_at, updated_at, deleted_at
`

func (q *Queries) TrashSlider(ctx context.Context, sliderID int32) (*Slider, error) {
	row := q.db.QueryRowContext(ctx, trashSlider, sliderID)
	var i Slider
	err := row.Scan(
		&i.SliderID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateSlider = `-- name: UpdateSlider :one
UPDATE sliders
SET name = $2,
    image = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE slider_id = $1
AND deleted_at IS NULL
RETURNING slider_id, name, image, created_at, updated_at, deleted_at
`

type UpdateSliderParams struct {
	SliderID int32  `json:"slider_id"`
	Name     string `json:"name"`
	Image    string `json:"image"`
}

func (q *Queries) UpdateSlider(ctx context.Context, arg UpdateSliderParams) (*Slider, error) {
	row := q.db.QueryRowContext(ctx, updateSlider, arg.SliderID, arg.Name, arg.Image)
	var i Slider
	err := row.Scan(
		&i.SliderID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
